[package]
name = "compute_pi"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.8"
actix-web = "4.7.0"
reqwest = {version = "0.12.4",default-features = false, features = ["json","rustls-tls"]}